scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    email:
        enabled: true
        mailer: Symfony\Component\Mailer\MailerInterface
        sender_email: "testSYMFONY25@yandex.com"
        sender_name: "My Symfony App"