controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

employees_index:
    path: /employees
    controller: App\Controller\EmployeeController::index

employees_create:
    path: /employees/create
    controller: App\Controller\EmployeeController::create

employees_edit:
    path: /employees/{id}/edit
    controller: App\Controller\EmployeeController::edit
    requirements:
        id: \d+

employees_destroy:
    path: /employees/{id}/delete
    controller: App\Controller\EmployeeController::delete
    methods: [DELETE]
    requirements:
        id: \d+

phone_index:
    path: /phones
    controller: App\Controller\PhoneController::index
    methods: GET

phone_new:
    path: /phone/new
    controller: App\Controller\PhoneController::new
    methods: GET|POST

phone_edit:
    path: /phone/edit/{id}
    controller: App\Controller\PhoneController::edit
    methods: GET|POST
    requirements:
        id: \d+

phone_delete:
    path: /phone/delete/{id}
    controller: App\Controller\PhoneController::delete
    methods: POST
    requirements:
        id: \d+

phone_add_to_user:
    path: /phone/add-to-user/{id}
    controller: App\Controller\PhoneController::addToUser
    methods: GET|POST
    requirements:
        id: \d+

user_delete:
    path: /user/delete/{id}
    controller: App\Controller\PhoneController::deleteUser
    methods: POST
    requirements:
        id: \d+

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: [GET]

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::profile

app_profile_update:
    path: /profile/update
    controller: App\Controller\ProfileController::updateProfile
    methods: [POST]

settings_show:
    path: /settings
    controller: App\Controller\SettingController::show
    methods: GET

apartment_index:
    path: /apartments
    controller: App\Controller\ApartmentController::index
    methods: GET

apartment_new:
    path: /apartment/new
    controller: App\Controller\ApartmentController::new
    methods: [GET, POST]

apartment_show:
    path: /apartment/{id}
    controller: App\Controller\ApartmentController::show
    methods: GET

apartment_edit:
    path: /apartment/{id}/edit
    controller: App\Controller\ApartmentController::edit
    methods: [GET, POST]

apartment_delete:
    path: /apartment/{id}
    controller: App\Controller\ApartmentController::delete
    methods: POST

app_credit_calculator:
    path: /credit-calculator
    controller: App\Controller\CreditCalculatorController::index

app_support:
    path: /support
    controller: App\Controller\SupportController::index
    methods: [GET, POST]

app_admin_support:
    path: /admin/support
    controller: App\Controller\SupportController::adminSupport
    methods: [GET]

app_admin_support_reply:
    path: /admin/support/{id}/reply
    controller: App\Controller\SupportController::replyToMessage
    methods: [POST]

app_chat:
    path: /chat
    controller: App\Controller\ChatController::index
    methods: [GET, POST]

app_admin_chat:
    path: /admin/chat
    controller: App\Controller\AdminChatController::index
    methods: [GET]

app_admin_chat_view:
    path: /admin/chat/{id}
    controller: App\Controller\AdminChatController::viewChat
    methods: [GET, POST]

app_reset_password_request:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::request
    methods: [GET, POST]

app_reset_password_verify:
    path: /reset-password/verify
    controller: App\Controller\ResetPasswordController::verify
    methods: [GET, POST]

app_forgot_password:
    path: /forgot-password
    controller: App\Controller\SecurityController::forgotPassword
    methods: [GET, POST]

app_change_password_page:
    path: /profile/change-password
    controller: App\Controller\ProfileController::changePasswordPage
    methods: [GET, POST]

app_payment:
    path: /payment
    controller: App\Controller\PaymentController::index
    methods: [GET, POST]

property_index:
    path: /properties
    controller: App\Controller\PropertyController::index
    methods: GET

property_show:
    path: /property/{id}
    controller: App\Controller\PropertyController::show
    methods: GET
    requirements:
        id: '\d+'

property_new:
    path: /property/new
    controller: App\Controller\PropertyController::new
    methods: [GET, POST]

property_edit:
    path: /property/{id}/edit
    controller: App\Controller\PropertyController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

property_delete:
    path: /property/{id}/delete
    controller: App\Controller\PropertyController::delete
    methods: POST
    requirements:
        id: '\d+'

about_us:
    path: /about-us
    controller: App\Controller\PropertyController::index

external_rate_index:
    path: /external-rate
    controller: App\Controller\ExternalRateController::index
    methods: GET

external_rate_new:
    path: /external-rate/new
    controller: App\Controller\ExternalRateController::new
    methods: [GET, POST]

external_rate_edit:
    path: /external-rate/{id}/edit
    controller: App\Controller\ExternalRateController::edit
    methods: [GET, POST]
    requirements:
        id: \d+

external_rate_delete:
    path: /external-rate/{id}/delete
    controller: App\Controller\ExternalRateController::delete
    methods: [DELETE]
    requirements:
        id: \d+

unit_index:
    path: /admin/unit
    controller: App\Controller\UnitController::index
    methods: GET

unit_new:
    path: /admin/unit/new
    controller: App\Controller\UnitController::new
    methods: [GET, POST]

unit_show:
    path: /admin/unit/{id}
    controller: App\Controller\UnitController::show
    methods: GET

unit_edit:
    path: /admin/unit/{id}/edit
    controller: App\Controller\UnitController::edit
    methods: [GET, POST]

unit_delete:
    path: /admin/unit/{id}
    controller: App\Controller\UnitController::delete
    methods: POST

arrival_journal_index:
    path: /admin/arrival-journal
    controller: App\Controller\ArrivalJournalController::index
    methods: GET

arrival_journal_new:
    path: /admin/arrival-journal/new
    controller: App\Controller\ArrivalJournalController::new
    methods: [GET, POST]

arrival_journal_show:
    path: /admin/arrival-journal/{id}
    controller: App\Controller\ArrivalJournalController::show
    methods: GET

arrival_journal_edit:
    path: /admin/arrival-journal/{id}/edit
    controller: App\Controller\ArrivalJournalController::edit
    methods: [GET, POST]

arrival_journal_delete:
    path: /admin/arrival-journal/{id}
    controller: App\Controller\ArrivalJournalController::delete
    methods: POST

counterparty_index:
    path: /counterparty
    controller: App\Controller\CounterpartyController::index
    methods: GET

counterparty_new:
    path: /counterparty/new
    controller: App\Controller\CounterpartyController::new
    methods: [GET, POST]

counterparty_show:
    path: /counterparty/{id}
    controller: App\Controller\CounterpartyController::show
    methods: GET

counterparty_edit:
    path: /counterparty/{id}/edit
    controller: App\Controller\CounterpartyController::edit
    methods: [GET, POST]

counterparty_delete:
    path: /counterparty/{id}
    controller: App\Controller\CounterpartyController::delete
    methods: POST

arrival_journal_detail_edit:
    path: /admin/arrival-journal-detail/{id}/edit
    controller: App\Controller\ArrivalJournalController::editDetail
    methods: [GET, POST]
    requirements:
        id: \d+


app_verify_2fa:
    path: /verify-2fa
    controller: App\Controller\Verify2FAController::verify2FA
    methods: [GET, POST]

app_enable_2fa:
    path: /enable-2fa
    controller: App\Controller\TwoFactorAuthController::enable2FA
    methods: [GET, POST]

app_disable_2fa:
    path: /disable-2fa
    controller: App\Controller\TwoFactorAuthController::disable2FA
    methods: [GET, POST]

app_send_2fa_code:
    path: /send-2fa-code
    controller: App\Controller\SecurityController::send2FACode
    methods: [GET, POST]

# config/routes.yaml
suggest_address:
    path: /suggest-address
    controller: App\Controller\DaDataController::suggestAddress
    methods: [GET]

suggest_party:
    path: /suggest-party
    controller: App\Controller\DaDataController::suggestParty
    methods: [GET]

clean_name:
    path: /clean-name
    controller: App\Controller\DaDataController::cleanName
    methods: [GET]

geolocate_address:
    path: /geolocate-address
    controller: App\Controller\DaDataController::geolocateAddress
    methods: [GET]